---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install collections
      ansible.builtin.command: >-
        ansible-galaxy collection install -r {{ playbook_dir }}/../../requirements.yml
      changed_when: false
      delegate_to: localhost
